---
- hosts: all
  become: yes
  tasks:
    - name: yum Install Development Package
      yum:
        name: "@Development tools"
        state: present

    - name: yum Install Package
      yum:
        name: "{{ Packges }}"
        state: present
        update_cache: yes
      vars:
        Packges:
          - ntp
          - git
          - curl
          - vim
          - python
          - python-devel

    - name: get get-pip.py
      command: curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py

    - name: Install get-pip.py
      command: python get-pip.py

    - name: upgrade pip
      command: pip install --upgrade pip
# Docker-ce
    - name: yum Docker-ce Install Package
      yum:
        name: "{{ DcokerPackges }}"
        state: latest
        update_cache: yes
      vars:
        DcokerPackges:
          - yum-utils 
          - device-mapper-persistent-data
          - lvm2

    - name: add docker repo
      shell: "yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo"
      args:
        chdir: "/etc/yum.repos.d"
        creates: docker-ce.repo

    - name: install docker-ce
      yum: name=docker-ce state=present

    - name: add group
      user: name=vagrant groups=docker append=yes
      tags: dockerhost
      become: True

    - name: restart docker
      systemd:
        name: docker.service
        state: restarted
        daemon_reload: yes
        enabled: yes
        
    - name: pip upgrade
      pip:
        name: pip 
        extra_args: --upgrade 

    - name: setuptools upgrade
      pip:
        name: setuptools 
        extra_args: --upgrade 

    - name: pip install awscli
      pip:
        name: awscli

    - name: pip install aws-sam-cli
      pip:
        name: aws-sam-cli
        extra_args: --user

    - name: Cmd Install aws-sam-cli
      command: pip install --user aws-sam-cli
