---
- hosts: localhost
  remote_user: vagrant
  vars:
    ansible_usr: vagrant
  tasks:
    - name: Set authorized key
      authorized_key:
        user: vagrant
        state: present
        key: "{{ lookup('file', '/home/{{ ansible_usr }}/.ssh/id_rsa.pub') }}"