---

- hosts: all
  become: yes
  tasks:
  - name: Install a list of packages
    apt:
      name: "{{ packages }}"
      update_cache: yes
      state: latest
    vars:
      packages:
      - git
      - vim
      - python3-pip

  # Docker　Install
  - name: Install a Docker packages
    apt:
      name: "{{ docker_packages }}"
      update_cache: yes
      state: latest
    vars:
      docker_packages:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common

  - name: Check docker gpg key.
    shell: apt-key fingerprint 0EBFCD88 | grep 0EBFCD88
    register: docker_gpg
    ignore_errors: True
    changed_when: False

  - name: Add Docker’s official GPG key
    shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
    when: docker_gpg | failed

  - name: define lsb_release -cs
    shell: lsb_release -cs
    ignore_errors: True
    register: lsb_release

  - name: set up the stable repository
    shell: add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ lsb_release.stdout }} stable"

  - name: Install docker-ce.
    apt: name=docker-ce state=present update_cache=yes

  - name: add group
    user: name=vagrant groups=docker append=yes
    tags: dockerhost
    become: yes

  - name: docker-ce version
    command: docker --version
    register: docker_ver

  - name: docker-ce version
    debug:
      var: docker_ver.stdout

  - name: install python-pip
    apt: name="{{ item }}" state=present
    with_items:
      - python-pip

  - name: install docker-compose
    pip:
      name: docker-compose

# Settingfile Deploy
  - name: AWS configure file Dirctory Make
    file:
      path: /home/vagrant/.aws
      state: directory
      owner: vagrant
      group: vagrant
      mode: 0755

  - name: AWS configure file
    copy:
      src: config
      dest: /home/vagrant/.aws/config
      owner: vagrant
      group: vagrant
      mode: 0644

  - name: LocalStack credentials file
    copy:
      src: credentials
      dest: /home/vagrant/.aws/credentials
      owner: vagrant
      group: vagrant
      mode: 0644

# AWS CLI Install
  - name: pip install awscli
    pip:
      name: awscli
      executable: pip3

  - name: pip install aws-sam-cli
    pip:
      name: aws-sam-cli
      executable: pip3