---

- hosts: all
  become: ture
  tasks:
    - name: get get-pip.py
      command: curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py

    - name: Install get-pip.py
      command: python get-pip.py

    - name: upgrade pip
      command: pip install --upgrade pip
