# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.box_version = "1809.01"

  config.disksize.size = '40GB'
 
  # CPU Core, Memeory Setting
  config.vm.provider "virtualbox" do |vb|
    vb.cpus = 4
    vb.memory = "2048"
    vb.gui = true
  end

  if Vagrant.has_plugin?("vagrant-vbguest")
    # set auto_update to false, if you do NOT want to check the correct
    config.vbguest.auto_update = true
  end

  config.vm.synced_folder "./shareDir", "/vagrant", type: "virtualbox"

  config.vm.define "node1" do |node1|
    node1.vm.hostname = "node1"
    node1.vm.network :private_network, ip: "192.168.33.20"

    # VirtualBoxのGUI上の名前を設定する
    node1.vm.provider "virtualbox" do |vb|
      vb.name = config.vm.box.gsub(/\//, "_") + "_" + node1.vm.hostname
    end

    config.vm.provision "shell", inline: <<-SHELL
    sudo yum update grub2-common
    sudo yum install fwupdate-efi
    sudo LANG=C yum groupinstall "GNOME Desktop"
    sudo yum install -y epel-release
    sudo systemctl set-default graphical.target
    systemctl get-default
    sudo shutdown -r now
  SHELL

  end
end
